### ISSUE TITLE
Errors after 10 TV Shows

### ISSUE THREAD

**Issue by Jamie932** [timdp/kodi-missing-episodes#2]
When I run the command, the first 10 TV shows check against the TVDB successfully. On the 11th, I get errors related to the 'thumbnail' property.

TypeError: Cannot read property 'thumbnail' of undefined
    at XbmcApi.scrub (C:\kodi-missing-episodes\node_modules\xbmc\lib\XbmcApi.js:109:15)
    at Function.Media._result (C:\kodi-missing-episodes\node_modules\xbmc\lib\Media.js:26:21)
    at C:\kodi-missing-episodes\node_modules\xbmc\lib\Media.js:101:22
    at Immediate._onImmediate (C:\kodi-missing-episodes\node_modules\xbmc\node_modules\node-promise\promise.js:164:27)
    at processImmediate [as _immediateCallback](timers.js:358:17)

From previous event:
    at kodiGetEpisodes (C:\kodi-missing-episodes\kodi-missing-episodes.js:122:6)
    at processShow (C:\kodi-missing-episodes\kodi-missing-episodes.js:226:48)
    at C:\kodi-missing-episodes\node_modules\qlimit\index.js:49:26 

NodeJS version: 0.12.4
Kodi version: v14.2
OS: Windows 8 x64

**Comment by timdp** [comment]
Judging by the stack trace, that looks like an issue with [node-xbmc](https://github.com/moul/node-xbmc). Could you report it there and reference this issue? To check which series it's having trouble with, you can pass --verbose --concurrency=1 to this script. Thanks!
