### ISSUE TITLE
Error: Show not found

### ISSUE THREAD

**Issue by b1n4ryj4n** [timdp/kodi-missing-episodes#3]
In my case occurs always this error message and the script end.

Error: Show not found: Akame ga Kill: Schwerter der Assassinen
    at D:\PortableApps\Kodi Tools\kodi-missing-episodes\lib\
tvdb.js:32:17
    at _fulfilled (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:796:13)
    at D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:604:44
    at runSingle (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:137:13)
    at flush (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:125:13)
From previous event:
    at defer (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:582:19)
    at Promise.then (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:828:20)
    at tvdbGetEpisodes (D:\PortableApps\Kodi Tools\kodi-missing-episodes\kodi-missing-episodes.js:94:6)
    at processShow (D:\PortableApps\Kodi Tools\kodi-missing-episodes\kodi-missing-episodes.js:227:24)
    at D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\qlimit\index.js:49:26
    at _fulfilled (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:796:13)
    at D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:604:44
    at runSingle (D:\PortableApps\Kodi Tools\kodi-missing-episodes\node_modules\q\q.js:137:13)

**Comment by timdp** [comment]
TheTVDB.com only has information for that show in German, apparently. By default, kodi-missing-episodes only searches in the English version. However, you can override this by listing the languages you want in `config.json`:

``` json
{
  "tvdb": {
    "apiKey": "...",
    "languages": ["en", "de"]
  }
}
```

A list of supported languages can be found [here](http://thetvdb.com/wiki/index.php/Multi_Language). Keep in mind that, because of the way TheTVDB.com works, every language that you add will slow down the script.

**Comment by b1n4ryj4n** [comment]
Thank you!
