### ISSUE TITLE
Error with show "11.22.63"

### ISSUE THREAD

**Issue by thedroid** [timdp/kodi-missing-episodes#9]
`Processing show 3 of 37: 11.22.63
Finding TheTVDB ID for 11.22.63
Getting Kodi episodes for 11.22.63 (#273)
TypeError: Cannot read property 'length' of undefined
    at EventEmitter.<anonymous> (D:\node\kodi-missing\lib\output\text.js:69:20)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at D:\node\kodi-missing\kodi-missing-episodes.js:86:14
From previous event:
    at tvdbGetEpisodes (D:\node\kodi-missing\kodi-missing-episodes.js:94:6)
    at processShow (D:\node\kodi-missing\kodi-missing-episodes.js:227:24)
    at D:\node\kodi-missing\node_modules\qlimit\index.js:49:26`

**Comment by timdp** [comment]
I'm unable to reproduce this, but thanks to the stack trace you posted, I'm pretty sure it's being caused by the TVDB API returning `undefined` for a show. Depending on the concurrency setting, it may or may not be the show title from the log.

If my assumption is correct, you should be able to fix it by going into `lib/tvdb.js` and changing line 43 from

```js
return info.episodes
```

to:

```js
if (!info.episodes) {
  console.warn('No episodes: %s', show.id)
  return []
}
return info.episodes
```

That should log the problematic show ID and fail silently. It'd be great if you could share that, because that would allow me to debug it further.
